server:
  port: 7000

app:
  base-uri: ${APP_BASE_URI:http://localhost:7000/}

spring:

  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/kilo_it_spring
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false

  security:
    user:
      name: sattya
      password: 123
    public-key: classpath:certs/public.pem
    private-key: classpath:certs/private.pem

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB