server:
  port: 7000

app:
  base-uri: ${APP_BASE_URI:http://localhost:7000/}
  api-version: ${API_VERSION:api/v1/}

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/kilo_it_spring
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false

  security:
    user:
      name: sattya
      password: 123

    allow-origin: "*"
    allowed-header: Authorization,Content-Type,User-Agent,X-Forwarded
    allowed-method: POST,PUT,PATCH,DELETE,GET,OPTIONS

    public-key: classpath:certs/public.pem
    private-key: classpath:certs/private.pem

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        query:
          fail_on_pagination_over_collection_fetch: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pisethsattya33@gmail.com
    password: nsli hqbp vzua dsgy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true